version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      GKB_DB_HOST: db
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: orientdb:3.0
    environment:
      ORIENTDB_ROOT_PASSWORD: root
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
